services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # MONGO_URI and JWT_SECRET should be set in Northflank dashboard
    volumes:
      - ./assets:/app/assets

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend 