version: '1.0'
name: regent-portal-backend
description: Regent Portal Backend API Service

services:
  - name: backend
    type: web
    image: node:18-alpine
    workingDir: /app/server
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - port: 3000
        protocol: http
    environment:
      - NODE_ENV=production
      - PORT=3000
    envFrom:
      - secret: mongo-uri
    resources:
      cpu: 0.5
      memory: 512Mi
    healthCheck:
      path: /api/test
      port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    scaling:
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilization: 70

secrets:
  - name: mongo-uri
    description: MongoDB Atlas connection string
    type: env 