version: '1.0'
name: regent-portal-frontend
description: Regent Portal Frontend Application

services:
  - name: frontend
    type: web
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - port: 80
        protocol: http
    environment:
      - API_URL=${API_URL}
    resources:
      cpu: 0.25
      memory: 256Mi
    healthCheck:
      path: /
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    scaling:
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilization: 60 